table dim_calendar

	column date
		dataType: dateTime
		sourceColumn: date
		formatString: yyyy-mm-dd
		isKey

	column year
		dataType: int64
		sourceColumn: year
		formatString: #,0

	column quarter
		dataType: string
		sourceColumn: quarter
		formatString: #,0.0000

	column month
		dataType: int64
		sourceColumn: month
		formatString: #,0

	column month_name
		dataType: string
		sourceColumn: month_name
		formatString: #,0.0000

	column week_of_year
		dataType: int64
		sourceColumn: week_of_year
		formatString: #,0

	column day_of_week
		dataType: int64
		sourceColumn: day_of_week
		formatString: #,0

	column day_name
		dataType: string
		sourceColumn: day_name
		formatString: #,0.0000

	column is_weekend
		dataType: int64
		sourceColumn: is_weekend
		formatString: #,0

	column is_month_end
		dataType: int64
		sourceColumn: is_month_end
		formatString: #,0

	column is_payday_window
		dataType: int64
		sourceColumn: is_payday_window
		formatString: #,0

	column is_school_holiday
		dataType: int64
		sourceColumn: is_school_holiday
		formatString: #,0

	column is_bank_holiday
		dataType: int64
		sourceColumn: is_bank_holiday
		formatString: #,0

	column bank_holiday_name
		dataType: string
		sourceColumn: bank_holiday_name
		formatString: #,0.0000

	column is_easter_period
		dataType: int64
		sourceColumn: is_easter_period
		formatString: #,0

	column is_christmas_period
		dataType: int64
		sourceColumn: is_christmas_period
		formatString: #,0

	column is_black_friday_period
		dataType: int64
		sourceColumn: is_black_friday_period
		formatString: #,0

	column is_heatwave
		dataType: int64
		sourceColumn: is_heatwave
		formatString: #,0

	column weather_condition
		dataType: string
		sourceColumn: weather_condition
		formatString: #,0.0000

	column temperature_celsius
		dataType: double
		sourceColumn: temperature_celsius
		formatString: #,0.0000

	partition dim_calendar = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_calendar.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"date", type date}, {"year", Int64.Type}, {"quarter", type text}, {"month", Int64.Type}, {"month_name", type text}, {"week_of_year", Int64.Type}, {"day_of_week", Int64.Type}, {"day_name", type text}, {"is_weekend", Int64.Type}, {"is_month_end", Int64.Type}, {"is_payday_window", Int64.Type}, {"is_school_holiday", Int64.Type}, {"is_bank_holiday", Int64.Type}, {"bank_holiday_name", type text}, {"is_easter_period", Int64.Type}, {"is_christmas_period", Int64.Type}, {"is_black_friday_period", Int64.Type}, {"is_heatwave", Int64.Type}, {"weather_condition", type text}, {"temperature_celsius", type number}})
				in
				    Typed
