table dim_store

	column store_id
		dataType: string
		sourceColumn: store_id
		formatString: #,0.0000

	column store_name
		dataType: string
		sourceColumn: store_name
		formatString: #,0.0000

	column city
		dataType: string
		sourceColumn: city
		formatString: #,0.0000

	column region
		dataType: string
		sourceColumn: region
		formatString: #,0.0000

	column country
		dataType: string
		sourceColumn: country
		formatString: #,0.0000

	column store_format
		dataType: string
		sourceColumn: store_format
		formatString: #,0.0000

	column floor_area_sqm
		dataType: int64
		sourceColumn: floor_area_sqm
		formatString: #,0

	column average_daily_footfall
		dataType: int64
		sourceColumn: average_daily_footfall
		formatString: #,0

	column competition_intensity_score
		dataType: int64
		sourceColumn: competition_intensity_score
		formatString: #,0

	column store_income_index
		dataType: double
		sourceColumn: store_income_index
		formatString: #,0.0000

	column local_deprivation_decile
		dataType: int64
		sourceColumn: local_deprivation_decile
		formatString: #,0

	column rollout_cohort
		dataType: int64
		sourceColumn: rollout_cohort
		formatString: #,0

	partition dim_store = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_store.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"store_id", type text}, {"store_name", type text}, {"city", type text}, {"region", type text}, {"country", type text}, {"store_format", type text}, {"floor_area_sqm", Int64.Type}, {"average_daily_footfall", Int64.Type}, {"competition_intensity_score", Int64.Type}, {"store_income_index", type number}, {"local_deprivation_decile", Int64.Type}, {"rollout_cohort", Int64.Type}})
				in
				    Typed
