table dose_response

	measure 'Dose Response Points' =
			COUNTROWS ( dose_response )

	measure 'CI Coverage %' =
			DIVIDE (
			    CALCULATE ( COUNTROWS ( dose_response ), dose_response[ci_covers_truth] = 1 ),
			    COUNTROWS ( dose_response )
			) * 100
		formatString: #,0.00

	measure 'Max Recovery Error' =
			MAXX ( dose_response, ABS ( dose_response[error] ) )

	measure 'Mean Lift at 20% Discount' =
			CALCULATE (
			    AVERAGE ( dose_response[estimated_lift_pct] ),
			    dose_response[discount_pct] = 20
			)
		formatString: #,0.00

	measure 'Estimated Lift %' =
			AVERAGE ( dose_response[estimated_lift_pct] )
		formatString: #,0.00

	measure 'True Lift %' =
			AVERAGE ( dose_response[true_lift_pct] )
		formatString: #,0.00

	measure 'Lift Recovery Gap pp' =
			[Estimated Lift %] - [True Lift %]
		formatString: #,0.00

	column segment
		dataType: string
		sourceColumn: segment
		formatString: #,0.0000

	column discount_pct
		dataType: int64
		sourceColumn: discount_pct
		formatString: #,0

	column estimate
		dataType: double
		sourceColumn: estimate
		formatString: #,0.0000

	column ci_low
		dataType: double
		sourceColumn: ci_low
		formatString: #,0.0000

	column ci_high
		dataType: double
		sourceColumn: ci_high
		formatString: #,0.0000

	column true_effect
		dataType: double
		sourceColumn: true_effect
		formatString: #,0.0000

	column error
		dataType: double
		sourceColumn: error
		formatString: #,0.0000

	column ci_covers_truth
		dataType: int64
		sourceColumn: ci_covers_truth
		formatString: #,0

	column estimated_lift_pct
		dataType: double
		sourceColumn: estimated_lift_pct
		formatString: #,0.00

	column true_lift_pct
		dataType: double
		sourceColumn: true_lift_pct
		formatString: #,0.00

	partition dose_response = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dose_response.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"segment", type text}, {"discount_pct", Int64.Type}, {"estimate", type number}, {"ci_low", type number}, {"ci_high", type number}, {"true_effect", type number}, {"error", type number}, {"ci_covers_truth", Int64.Type}, {"estimated_lift_pct", type number}, {"true_lift_pct", type number}})
				in
				    Typed
