table promo_plan_draws

	column draw
		dataType: int64
		sourceColumn: draw
		formatString: #,0

	column profit_gbp
		dataType: double
		sourceColumn: profit_gbp
		formatString: \£#,0.00;(\£#,0.00);\£#,0.00

	partition promo_plan_draws = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "promo_plan_draws.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"draw", Int64.Type}, {"profit_gbp", type number}})
				in
				    Typed
